// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: fanout.proto

package fanout

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostTopic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host  string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Topic string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *HostTopic) Reset() {
	*x = HostTopic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fanout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostTopic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTopic) ProtoMessage() {}

func (x *HostTopic) ProtoReflect() protoreflect.Message {
	mi := &file_fanout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostTopic.ProtoReflect.Descriptor instead.
func (*HostTopic) Descriptor() ([]byte, []int) {
	return file_fanout_proto_rawDescGZIP(), []int{0}
}

func (x *HostTopic) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HostTopic) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fanout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_fanout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_fanout_proto_rawDescGZIP(), []int{1}
}

func (x *Host) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

var File_fanout_proto protoreflect.FileDescriptor

var file_fanout_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x09, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x1a, 0x0a, 0x04, 0x48, 0x6f,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x32, 0xb2, 0x01, 0x0a, 0x06, 0x46, 0x61, 0x6e, 0x6f, 0x75,
	0x74, 0x12, 0x36, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x11,
	0x2e, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x38, 0x0a, 0x0b, 0x55, 0x6e, 0x73,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x11, 0x2e, 0x66, 0x61, 0x6e, 0x6f, 0x75,
	0x74, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x12, 0x36, 0x0a, 0x0e, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x0c, 0x2e, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x2c, 0x5a, 0x2a, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x66, 0x72, 0x6f, 0x7a, 0x61,
	0x6c, 0x6d, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x66, 0x61, 0x6e, 0x6f, 0x75, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_fanout_proto_rawDescOnce sync.Once
	file_fanout_proto_rawDescData = file_fanout_proto_rawDesc
)

func file_fanout_proto_rawDescGZIP() []byte {
	file_fanout_proto_rawDescOnce.Do(func() {
		file_fanout_proto_rawDescData = protoimpl.X.CompressGZIP(file_fanout_proto_rawDescData)
	})
	return file_fanout_proto_rawDescData
}

var file_fanout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fanout_proto_goTypes = []interface{}{
	(*HostTopic)(nil),     // 0: fanout.HostTopic
	(*Host)(nil),          // 1: fanout.Host
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_fanout_proto_depIdxs = []int32{
	0, // 0: fanout.Fanout.Subscribe:input_type -> fanout.HostTopic
	0, // 1: fanout.Fanout.Unsubscribe:input_type -> fanout.HostTopic
	1, // 2: fanout.Fanout.UnsubscribeAll:input_type -> fanout.Host
	2, // 3: fanout.Fanout.Subscribe:output_type -> google.protobuf.Empty
	2, // 4: fanout.Fanout.Unsubscribe:output_type -> google.protobuf.Empty
	2, // 5: fanout.Fanout.UnsubscribeAll:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fanout_proto_init() }
func file_fanout_proto_init() {
	if File_fanout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fanout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostTopic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_fanout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fanout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fanout_proto_goTypes,
		DependencyIndexes: file_fanout_proto_depIdxs,
		MessageInfos:      file_fanout_proto_msgTypes,
	}.Build()
	File_fanout_proto = out.File
	file_fanout_proto_rawDesc = nil
	file_fanout_proto_goTypes = nil
	file_fanout_proto_depIdxs = nil
}
